services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports: ["2181:2181"]

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    depends_on: [zookeeper]
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://127.0.0.1:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1


  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: payguard
      POSTGRES_PASSWORD: payguard
      POSTGRES_DB: payguard
    ports:
      - "5433:5432"

  kafka-init:
    image: confluentinc/cp-kafka:7.5.3
    depends_on:
      - kafka
    entrypoint: ["/bin/bash", "-c", "/scripts/kafka_init.sh"]
    environment:
      KAFKA_BOOTSTRAP: "kafka:29092"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      TOPIC_NAME: "txns"
      TOPIC_PARTITIONS: "3"
      TOPIC_REPLICATION: "1"
    volumes:
      - ../scripts:/scripts:ro

    restart: "no"

